-- Insert Essential Data Migration
-- This migration populates countries, timezones, and subscription plans

-- Insert countries data
INSERT INTO countries (name, code, continent) VALUES
-- North America
('United States', 'US', 'North America'),
('Canada', 'CA', 'North America'),
('Mexico', 'MX', 'North America'),

-- Europe
('United Kingdom', 'GB', 'Europe'),
('France', 'FR', 'Europe'),
('Germany', 'DE', 'Europe'),
('Italy', 'IT', 'Europe'),
('Spain', 'ES', 'Europe'),
('Netherlands', 'NL', 'Europe'),
('Sweden', 'SE', 'Europe'),
('Norway', 'NO', 'Europe'),
('Denmark', 'DK', 'Europe'),
('Finland', 'FI', 'Europe'),
('Iceland', 'IS', 'Europe'),
('Ireland', 'IE', 'Europe'),
('Switzerland', 'CH', 'Europe'),
('Austria', 'AT', 'Europe'),
('Belgium', 'BE', 'Europe'),
('Luxembourg', 'LU', 'Europe'),
('Portugal', 'PT', 'Europe'),
('Poland', 'PL', 'Europe'),
('Czech Republic', 'CZ', 'Europe'),
('Slovakia', 'SK', 'Europe'),
('Hungary', 'HU', 'Europe'),
('Slovenia', 'SI', 'Europe'),
('Croatia', 'HR', 'Europe'),
('Bosnia and Herzegovina', 'BA', 'Europe'),
('Serbia', 'RS', 'Europe'),
('Montenegro', 'ME', 'Europe'),
('Albania', 'AL', 'Europe'),
('North Macedonia', 'MK', 'Europe'),
('Bulgaria', 'BG', 'Europe'),
('Romania', 'RO', 'Europe'),
('Greece', 'GR', 'Europe'),
('Estonia', 'EE', 'Europe'),
('Latvia', 'LV', 'Europe'),
('Lithuania', 'LT', 'Europe'),

-- Asia
('Japan', 'JP', 'Asia'),
('South Korea', 'KR', 'Asia'),
('China', 'CN', 'Asia'),
('India', 'IN', 'Asia'),
('Indonesia', 'ID', 'Asia'),
('Thailand', 'TH', 'Asia'),
('Vietnam', 'VN', 'Asia'),
('Malaysia', 'MY', 'Asia'),
('Singapore', 'SG', 'Asia'),
('Philippines', 'PH', 'Asia'),
('Taiwan', 'TW', 'Asia'),
('Hong Kong', 'HK', 'Asia'),
('Macau', 'MO', 'Asia'),
('Bangladesh', 'BD', 'Asia'),
('Pakistan', 'PK', 'Asia'),
('Sri Lanka', 'LK', 'Asia'),
('Nepal', 'NP', 'Asia'),
('Bhutan', 'BT', 'Asia'),
('Maldives', 'MV', 'Asia'),
('Afghanistan', 'AF', 'Asia'),
('Iran', 'IR', 'Asia'),
('Israel', 'IL', 'Asia'),
('Iraq', 'IQ', 'Asia'),
('Kuwait', 'KW', 'Asia'),
('Qatar', 'QA', 'Asia'),
('Bahrain', 'BH', 'Asia'),
('Oman', 'OM', 'Asia'),
('Armenia', 'AM', 'Asia'),
('Georgia', 'GE', 'Asia'),
('Azerbaijan', 'AZ', 'Asia'),
('Uzbekistan', 'UZ', 'Asia'),
('Kazakhstan', 'KZ', 'Asia'),

-- Australia & Oceania
('Australia', 'AU', 'Oceania'),
('New Zealand', 'NZ', 'Oceania'),
('Fiji', 'FJ', 'Oceania'),
('Guam', 'GU', 'Oceania'),
('Northern Mariana Islands', 'MP', 'Oceania'),
('Papua New Guinea', 'PG', 'Oceania'),

-- Africa
('Egypt', 'EG', 'Africa'),
('South Africa', 'ZA', 'Africa'),
('Nigeria', 'NG', 'Africa'),
('Morocco', 'MA', 'Africa'),
('Algeria', 'DZ', 'Africa'),
('Tunisia', 'TN', 'Africa'),
('Libya', 'LY', 'Africa'),
('Sudan', 'SD', 'Africa'),
('Ethiopia', 'ET', 'Africa'),
('Kenya', 'KE', 'Africa'),
('Tanzania', 'TZ', 'Africa'),
('Uganda', 'UG', 'Africa'),
('Democratic Republic of the Congo', 'CD', 'Africa'),
('Angola', 'AO', 'Africa'),
('Zimbabwe', 'ZW', 'Africa'),
('Zambia', 'ZM', 'Africa'),
('Botswana', 'BW', 'Africa'),
('Namibia', 'NA', 'Africa'),
('Lesotho', 'LS', 'Africa'),
('Eswatini', 'SZ', 'Africa'),
('Mozambique', 'MZ', 'Africa'),
('Malawi', 'MW', 'Africa'),
('Burundi', 'BI', 'Africa'),
('Rwanda', 'RW', 'Africa'),
('Djibouti', 'DJ', 'Africa'),
('Eritrea', 'ER', 'Africa'),
('Somalia', 'SO', 'Africa'),
('Senegal', 'SN', 'Africa'),
('Mali', 'ML', 'Africa'),
('Burkina Faso', 'BF', 'Africa'),
('Ghana', 'GH', 'Africa'),
('Ivory Coast', 'CI', 'Africa'),
('Liberia', 'LR', 'Africa'),
('Sierra Leone', 'SL', 'Africa'),
('Guinea', 'GN', 'Africa'),
('Guinea-Bissau', 'GW', 'Africa'),
('Gambia', 'GM', 'Africa'),
('Mauritania', 'MR', 'Africa'),
('Western Sahara', 'EH', 'Africa'),

-- South America
('Brazil', 'BR', 'South America'),
('Argentina', 'AR', 'South America'),
('Chile', 'CL', 'South America'),
('Colombia', 'CO', 'South America'),
('Peru', 'PE', 'South America'),
('Venezuela', 'VE', 'South America'),
('Ecuador', 'EC', 'South America'),
('Bolivia', 'BO', 'South America'),
('Paraguay', 'PY', 'South America'),
('Uruguay', 'UY', 'South America'),
('Guyana', 'GY', 'South America'),
('Suriname', 'SR', 'South America'),
('French Guiana', 'GF', 'South America'),

-- Central America
('Guatemala', 'GT', 'Central America'),
('Belize', 'BZ', 'Central America'),
('El Salvador', 'SV', 'Central America'),
('Honduras', 'HN', 'Central America'),
('Nicaragua', 'NI', 'Central America'),
('Costa Rica', 'CR', 'Central America'),
('Panama', 'PA', 'Central America')
ON CONFLICT (code) DO NOTHING;

-- Insert comprehensive timezones data
INSERT INTO timezones (name, display_name, offset_hours, offset_minutes, region, country_id, city) 
SELECT tz.name, tz.display_name, tz.offset_hours, tz.offset_minutes, tz.region, c.id, tz.city
FROM (VALUES
  -- North America
  ('America/New_York', 'Eastern Time (New York)', -5, 0, 'North America', 'US', 'New York'),
  ('America/Chicago', 'Central Time (Chicago)', -6, 0, 'North America', 'US', 'Chicago'),
  ('America/Denver', 'Mountain Time (Denver)', -7, 0, 'North America', 'US', 'Denver'),
  ('America/Los_Angeles', 'Pacific Time (Los Angeles)', -8, 0, 'North America', 'US', 'Los Angeles'),
  ('America/Anchorage', 'Alaska Time (Anchorage)', -9, 0, 'North America', 'US', 'Anchorage'),
  ('Pacific/Honolulu', 'Hawaii Time (Honolulu)', -10, 0, 'North America', 'US', 'Honolulu'),
  ('America/Toronto', 'Eastern Time (Toronto)', -5, 0, 'North America', 'CA', 'Toronto'),
  ('America/Vancouver', 'Pacific Time (Vancouver)', -8, 0, 'North America', 'CA', 'Vancouver'),
  ('America/Mexico_City', 'Central Time (Mexico City)', -6, 0, 'North America', 'MX', 'Mexico City'),
  
  -- Europe
  ('Europe/London', 'Greenwich Mean Time (London)', 0, 0, 'Europe', 'GB', 'London'),
  ('Europe/Paris', 'Central European Time (Paris)', 1, 0, 'Europe', 'FR', 'Paris'),
  ('Europe/Berlin', 'Central European Time (Berlin)', 1, 0, 'Europe', 'DE', 'Berlin'),
  ('Europe/Rome', 'Central European Time (Rome)', 1, 0, 'Europe', 'IT', 'Rome'),
  ('Europe/Madrid', 'Central European Time (Madrid)', 1, 0, 'Europe', 'ES', 'Madrid'),
  ('Europe/Amsterdam', 'Central European Time (Amsterdam)', 1, 0, 'Europe', 'NL', 'Amsterdam'),
  ('Europe/Stockholm', 'Central European Time (Stockholm)', 1, 0, 'Europe', 'SE', 'Stockholm'),
  ('Europe/Oslo', 'Central European Time (Oslo)', 1, 0, 'Europe', 'NO', 'Oslo'),
  ('Europe/Copenhagen', 'Central European Time (Copenhagen)', 1, 0, 'Europe', 'DK', 'Copenhagen'),
  ('Europe/Helsinki', 'Eastern European Time (Helsinki)', 2, 0, 'Europe', 'FI', 'Helsinki'),
  ('Europe/Dublin', 'Greenwich Mean Time (Dublin)', 0, 0, 'Europe', 'IE', 'Dublin'),
  ('Europe/Zurich', 'Central European Time (Zurich)', 1, 0, 'Europe', 'CH', 'Zurich'),
  ('Europe/Vienna', 'Central European Time (Vienna)', 1, 0, 'Europe', 'AT', 'Vienna'),
  ('Europe/Brussels', 'Central European Time (Brussels)', 1, 0, 'Europe', 'BE', 'Brussels'),
  ('Europe/Luxembourg', 'Central European Time (Luxembourg)', 1, 0, 'Europe', 'LU', 'Luxembourg'),
  ('Europe/Lisbon', 'Western European Time (Lisbon)', 0, 0, 'Europe', 'PT', 'Lisbon'),
  ('Europe/Warsaw', 'Central European Time (Warsaw)', 1, 0, 'Europe', 'PL', 'Warsaw'),
  ('Europe/Prague', 'Central European Time (Prague)', 1, 0, 'Europe', 'CZ', 'Prague'),
  ('Europe/Athens', 'Eastern European Time (Athens)', 2, 0, 'Europe', 'GR', 'Athens'),
  ('Europe/Moscow', 'Moscow Time', 3, 0, 'Europe', NULL, 'Moscow'),
  
  -- Asia
  ('Asia/Tokyo', 'Japan Standard Time (Tokyo)', 9, 0, 'Asia', 'JP', 'Tokyo'),
  ('Asia/Seoul', 'Korea Standard Time (Seoul)', 9, 0, 'Asia', 'KR', 'Seoul'),
  ('Asia/Shanghai', 'China Standard Time (Shanghai)', 8, 0, 'Asia', 'CN', 'Shanghai'),
  ('Asia/Hong_Kong', 'Hong Kong Time', 8, 0, 'Asia', 'HK', 'Hong Kong'),
  ('Asia/Singapore', 'Singapore Time', 8, 0, 'Asia', 'SG', 'Singapore'),
  ('Asia/Kolkata', 'India Standard Time (Kolkata)', 5, 30, 'Asia', 'IN', 'Kolkata'),
  ('Asia/Dubai', 'Gulf Standard Time (Dubai)', 4, 0, 'Asia', NULL, 'Dubai'),
  ('Asia/Bangkok', 'Indochina Time (Bangkok)', 7, 0, 'Asia', 'TH', 'Bangkok'),
  ('Asia/Jakarta', 'Western Indonesia Time (Jakarta)', 7, 0, 'Asia', 'ID', 'Jakarta'),
  ('Asia/Manila', 'Philippine Time (Manila)', 8, 0, 'Asia', 'PH', 'Manila'),
  ('Asia/Kuala_Lumpur', 'Malaysia Time (Kuala Lumpur)', 8, 0, 'Asia', 'MY', 'Kuala Lumpur'),
  ('Asia/Ho_Chi_Minh', 'Indochina Time (Ho Chi Minh)', 7, 0, 'Asia', 'VN', 'Ho Chi Minh'),
  ('Asia/Dhaka', 'Bangladesh Time (Dhaka)', 6, 0, 'Asia', 'BD', 'Dhaka'),
  ('Asia/Karachi', 'Pakistan Time (Karachi)', 5, 0, 'Asia', 'PK', 'Karachi'),
  ('Asia/Tehran', 'Iran Time (Tehran)', 3, 30, 'Asia', 'IR', 'Tehran'),
  ('Asia/Jerusalem', 'Israel Time (Jerusalem)', 2, 0, 'Asia', 'IL', 'Jerusalem'),
  ('Asia/Riyadh', 'Arabia Standard Time (Riyadh)', 3, 0, 'Asia', NULL, 'Riyadh'),
  
  -- Australia & Oceania
  ('Australia/Sydney', 'Australian Eastern Time (Sydney)', 10, 0, 'Oceania', 'AU', 'Sydney'),
  ('Australia/Melbourne', 'Australian Eastern Time (Melbourne)', 10, 0, 'Oceania', 'AU', 'Melbourne'),
  ('Australia/Brisbane', 'Australian Eastern Time (Brisbane)', 10, 0, 'Oceania', 'AU', 'Brisbane'),
  ('Australia/Perth', 'Australian Western Time (Perth)', 8, 0, 'Oceania', 'AU', 'Perth'),
  ('Australia/Adelaide', 'Australian Central Time (Adelaide)', 9, 30, 'Oceania', 'AU', 'Adelaide'),
  ('Australia/Darwin', 'Australian Central Time (Darwin)', 9, 30, 'Oceania', 'AU', 'Darwin'),
  ('Pacific/Auckland', 'New Zealand Time (Auckland)', 12, 0, 'Oceania', 'NZ', 'Auckland'),
  ('Pacific/Fiji', 'Fiji Time', 12, 0, 'Oceania', 'FJ', 'Suva'),
  ('Pacific/Guam', 'Chamorro Time (Guam)', 10, 0, 'Oceania', 'GU', 'Guam'),
  
  -- Africa
  ('Africa/Cairo', 'Eastern European Time (Cairo)', 2, 0, 'Africa', 'EG', 'Cairo'),
  ('Africa/Johannesburg', 'South Africa Time (Johannesburg)', 2, 0, 'Africa', 'ZA', 'Johannesburg'),
  ('Africa/Lagos', 'West Africa Time (Lagos)', 1, 0, 'Africa', 'NG', 'Lagos'),
  ('Africa/Casablanca', 'Western European Time (Casablanca)', 0, 0, 'Africa', 'MA', 'Casablanca'),
  ('Africa/Algiers', 'Central European Time (Algiers)', 1, 0, 'Africa', 'DZ', 'Algiers'),
  ('Africa/Tunis', 'Central European Time (Tunis)', 1, 0, 'Africa', 'TN', 'Tunis'),
  ('Africa/Nairobi', 'East Africa Time (Nairobi)', 3, 0, 'Africa', 'KE', 'Nairobi'),
  ('Africa/Addis_Ababa', 'East Africa Time (Addis Ababa)', 3, 0, 'Africa', 'ET', 'Addis Ababa'),
  
  -- South America
  ('America/Sao_Paulo', 'Brasilia Time (São Paulo)', -3, 0, 'South America', 'BR', 'São Paulo'),
  ('America/Buenos_Aires', 'Argentina Time (Buenos Aires)', -3, 0, 'South America', 'AR', 'Buenos Aires'),
  ('America/Santiago', 'Chile Time (Santiago)', -3, 0, 'South America', 'CL', 'Santiago'),
  ('America/Bogota', 'Colombia Time (Bogotá)', -5, 0, 'South America', 'CO', 'Bogotá'),
  ('America/Lima', 'Peru Time (Lima)', -5, 0, 'South America', 'PE', 'Lima'),
  ('America/Caracas', 'Venezuela Time (Caracas)', -4, 0, 'South America', 'VE', 'Caracas'),
  ('America/Quito', 'Ecuador Time (Quito)', -5, 0, 'South America', 'EC', 'Quito'),
  ('America/La_Paz', 'Bolivia Time (La Paz)', -4, 0, 'South America', 'BO', 'La Paz'),
  ('America/Asuncion', 'Paraguay Time (Asunción)', -3, 0, 'South America', 'PY', 'Asunción'),
  ('America/Montevideo', 'Uruguay Time (Montevideo)', -3, 0, 'South America', 'UY', 'Montevideo')
) AS tz(name, display_name, offset_hours, offset_minutes, region, country_code, city)
LEFT JOIN countries c ON c.code = tz.country_code
ON CONFLICT (name) DO NOTHING;

-- Insert comprehensive subscription plans
INSERT INTO subscriptions (name, description, price_monthly, price_yearly, max_jobs, max_interviews_per_month, features, limits, stripe_product_id, stripe_price_id) VALUES
(
  'free', 
  'Free Tier - Perfect for trying out our platform', 
  0, 
  0, 
  2, 
  10, 
  '["Basic AI evaluations", "Email support", "Basic analytics", "Standard templates"]'::jsonb,
  '{"jobs_per_month": 2, "candidates_per_job": 10, "integrations": false, "team_collaboration": false, "export_reports": false}'::jsonb,
  'prod_free_placeholder',
  'price_free_placeholder'
),
(
  'pro', 
  'Pro Tier - For growing teams and enhanced features', 
  49, 
  490, 
  10, 
  100, 
  '["Advanced AI scoring", "Priority support", "Export reports", "Calendar integrations", "Custom templates", "Advanced analytics"]'::jsonb,
  '{"jobs_per_month": 10, "candidates_per_job": 100, "integrations": true, "team_collaboration": false, "export_reports": true}'::jsonb,
  'prod_professional_placeholder',
  'price_professional_placeholder'
),
(
  'business', 
  'Business Tier - For larger organizations', 
  149, 
  1490, 
  50, 
  500, 
  '["Unlimited jobs", "Team collaboration", "API access", "Advanced analytics", "Custom branding", "Dedicated support", "Async video interviews"]'::jsonb,
  '{"jobs_per_month": 50, "candidates_per_job": 500, "integrations": true, "team_collaboration": true, "export_reports": true, "api_access": true}'::jsonb,
  'prod_business_placeholder',
  'price_business_placeholder'
),
(
  'enterprise', 
  'Enterprise Tier - For large-scale operations', 
  999, 
  9990, 
  -1, 
  -1, 
  '["Unlimited everything", "Custom AI models", "SLAs", "Onboarding support", "Single Sign-On (SSO)", "Advanced security", "White-label options", "Dedicated account manager"]'::jsonb,
  '{"jobs_per_month": -1, "candidates_per_job": -1, "integrations": true, "team_collaboration": true, "export_reports": true, "api_access": true, "sso": true, "white_label": true}'::jsonb,
  'prod_enterprise_placeholder',
  'price_enterprise_placeholder'
)
ON CONFLICT (name) DO NOTHING; 